const names = require('./04-names')
const groupSession = require('./05-utils')
const data = require('./06-alternative-flavor')
require('./07-mind-grenade')
groupSession(names)
require('./08-os-module')
require('./09-path-module')
console.log(data)